Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/05/2023
Var
// Seção de Declarações das variáveis 
A, B , C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       A <- 2
       B <- 3
       C <- 5
       Escreva (C>=B^A)

Fimalgoritmo